name: dtspider
version: 0.0.1
description: A sample command-line application

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+2
  dio: 3.0.10
  moor_ffi: ^0.8.0
  uuid: 2.2.2
  image: ^2.1.18
  logging: ^0.11.4

  
dev_dependencies:
  json_to_model: ^1.3.13
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
